/* Project 0→100 V2.1: Wolfie 2x + Fuel Today */
(function(){
function install(){const frame=document.getElementById('app'),w=frame?.contentWindow,d=frame?.contentDocument;if(!w||!d||!w.data||!w.anchors)return;const date=w.today();w.data.wolfieWalksByDate=w.data.wolfieWalksByDate||{};w.data.fuelByDate=w.data.fuelByDate||{};if(w.data.wolfieWalksByDate[date]===undefined)w.data.wolfieWalksByDate[date]=w.anchors().wolfie?2:0;const meals=['Breakfast','Snack 1','Lunch','Snack 2','Dinner'],states=[['clean','🟢','Clean'],['okay','🟡',"Could've done better"],['rough','🔴','Fuck, I fucked up'],['fasting','⚪','Fasting']];
const style=d.createElement('style');style.textContent='.fuel-grid{display:grid;gap:8px;margin-top:12px}.fuel-row{display:grid;grid-template-columns:82px 1fr;gap:8px;align-items:center}.fuel-name{font-size:12px;font-weight:850}.fuel-options{display:grid;grid-template-columns:repeat(4,1fr);gap:5px}.fuel-btn{padding:8px 4px!important;font-size:10px!important;min-height:48px}.fuel-btn.active-clean{background:#173725!important;color:#caffdf!important;border:1px solid #315f48!important}.fuel-btn.active-okay{background:#3a3218!important;color:#ffe7a3!important;border:1px solid #7b6728!important}.fuel-btn.active-rough{background:#3a2026!important;color:#ffdce1!important;border:1px solid #75404a!important}.fuel-btn.active-fasting{background:#29313d!important;color:#f7f9fc!important;border:1px solid #596575!important}.wolfie-two{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:8px}.wolfie-two button{margin-top:0!important}.fuel-summary{margin-top:10px;padding:10px;border-radius:13px;background:#0d1219;border:1px solid #29313d}@media(max-width:430px){.fuel-row{grid-template-columns:1fr}.fuel-options{grid-template-columns:repeat(2,1fr)}}';d.head.appendChild(style);
const walks=()=>Number(w.data.wolfieWalksByDate[date]||0),fuel=()=>w.data.fuelByDate[date]||(w.data.fuelByDate[date]={}),persist=()=>localStorage.setItem('project0100_v4',JSON.stringify(w.data));
function meta(){const a=w.anchors(),n=(walks()>=2?1:0)+(a.workout?1:0)+(a.nutrition?1:0),p=d.getElementById('anchorCount');if(p)p.textContent=n+'/3'}
function wolfie(){d.querySelectorAll('#anchorGrid .anchor,#anchorGridDay .anchor').forEach(card=>{if(!card.textContent.includes('Walk Wolfie'))return;const n=walks();card.classList.toggle('done',n>=2);const l=card.querySelector('.small');if(l)l.textContent='Walk Wolfie • '+n+'/2';const old=[...card.children].find(x=>x.tagName==='BUTTON');if(old)old.remove();let box=card.querySelector('.wolfie-two');if(!box){box=d.createElement('div');box.className='wolfie-two';card.appendChild(box)}box.innerHTML='<button class="btn '+(n>=1?'good':'secondary')+' sm" data-walk="1">'+(n>=1?'✓ Walk 1':'Walk 1')+'</button><button class="btn '+(n>=2?'good':'secondary')+' sm" data-walk="2">'+(n>=2?'✓ Walk 2':'Walk 2')+'</button>';box.querySelectorAll('button').forEach(b=>b.onclick=()=>{const t=Number(b.dataset.walk);w.data.wolfieWalksByDate[date]=walks()===t?t-1:t;w.anchors().wolfie=walks()>=2;persist();wolfie();meta()})})}
function renderFuel(){const host=d.getElementById('fuelTodayV21');if(!host)return;const f=fuel();host.innerHTML=meals.map(m=>'<div class="fuel-row"><div class="fuel-name">'+m+'</div><div class="fuel-options">'+states.map(s=>'<button class="btn ghost fuel-btn '+(f[m]===s[0]?'active-'+s[0]:'')+'" data-meal="'+m+'" data-state="'+s[0]+'">'+s[1]+'<br>'+s[2]+'</button>').join('')+'</div></div>').join('')+'<div class="fuel-summary" id="fuelSummaryV21"></div>';host.querySelectorAll('button').forEach(b=>b.onclick=()=>{const f=fuel();f[b.dataset.meal]=f[b.dataset.meal]===b.dataset.state?null:b.dataset.state;const logged=meals.filter(m=>f[m]);if(logged.length===5&&!w.anchors().nutrition){w.anchors().nutrition=true;w.data.food=(w.data.food||0)+1}if(logged.length<5)w.anchors().nutrition=false;persist();renderFuel();meta()});const vals=meals.map(m=>f[m]).filter(Boolean),rough=vals.filter(x=>x==='rough').length,clean=vals.filter(x=>x==='clean').length,fasting=vals.filter(x=>x==='fasting').length;let msg=!vals.length?'Nothing logged yet. No judgment — just information.':rough?'One rough meal doesn’t own the day. Next decision resets the trajectory.':clean>=3?'Strong fuel day. Keep stacking the boring wins.':fasting?'Fasting logged neutrally — it neither helps nor hurts the score.':'Keep logging. The goal is awareness, not perfection.';d.getElementById('fuelSummaryV21').innerHTML='<div class="small">'+msg+'</div>'}
const body=d.getElementById('bodyView');if(body&&!d.getElementById('fuelCardV21')){const card=d.createElement('div');card.className='card';card.id='fuelCardV21';card.innerHTML='<div class="row"><div><div class="label">🥗 Fuel Today</div><div class="small">Five moments. Honest feedback. No all-or-nothing days.</div></div></div><div class="fuel-grid" id="fuelTodayV21"></div>';const recovery=[...body.querySelectorAll('.card')].find(x=>x.textContent.includes('Recovery / Fuel Check-In'));body.insertBefore(card,recovery||null)}
const original=w.render;w.render=function(){original();setTimeout(()=>{wolfie();renderFuel();meta()},0)};wolfie();renderFuel();meta()}
const frame=document.getElementById('app');if(frame)frame.addEventListener('load',()=>setTimeout(install,60));if(frame?.contentDocument?.readyState==='complete')setTimeout(install,60)
})();