/* Project 0→100 V2.1.2 — Wolfie 2x + Fuel Today. Parent-safe iframe patch. */
(function(){
const KEY='project0100_v4';
function install(){
 const frame=document.getElementById('app'),d=frame&&frame.contentDocument,w=frame&&frame.contentWindow;if(!d||!w)return;
 const date=new Date().toISOString().slice(0,10);
 const read=()=>{try{return JSON.parse(w.localStorage.getItem(KEY)||'{}')}catch(e){return {}}};
 const write=x=>w.localStorage.setItem(KEY,JSON.stringify(x));
 const getWalks=()=>{const x=read();x.wolfieWalksByDate=x.wolfieWalksByDate||{};return Number(x.wolfieWalksByDate[date]||0)};
 const setWalks=n=>{const x=read();x.wolfieWalksByDate=x.wolfieWalksByDate||{};x.wolfieWalksByDate[date]=n;write(x)};
 const meals=['Breakfast','Snack 1','Lunch','Snack 2','Dinner'];
 const states=[['clean','🟢','Clean'],['okay','🟡',"Could've done better"],['rough','🔴','Fuck, I fucked up'],['fasting','⚪','Fasting']];
 if(!d.getElementById('v212style')){const s=d.createElement('style');s.id='v212style';s.textContent='.wolfie-two{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:8px}.wolfie-two .btn{margin-top:0!important;padding:8px 4px!important;font-size:11px}.fuel-grid{display:grid;gap:9px;margin-top:12px}.fuel-row{display:grid;gap:6px}.fuel-name{font-size:12px;font-weight:900}.fuel-options{display:grid;grid-template-columns:repeat(2,1fr);gap:6px}.fuel-btn{padding:9px 5px!important;font-size:10px!important}.active-clean{background:#173725!important;color:#caffdf!important}.active-okay{background:#3a3218!important;color:#ffe7a3!important}.active-rough{background:#3a2026!important;color:#ffdce1!important}.active-fasting{background:#29313d!important;color:#fff!important}.fuel-summary{margin-top:10px;padding:10px;border-radius:13px;background:#0d1219;border:1px solid #29313d}';d.head.appendChild(s)}
 function wolfie(){d.querySelectorAll('#anchorGrid .anchor,#anchorGridDay .anchor').forEach(card=>{if(!card.textContent.includes('Walk Wolfie'))return;const n=getWalks();card.classList.toggle('done',n>=2);const label=[...card.querySelectorAll('div')].find(x=>x.textContent.trim()==='Walk Wolfie'||x.textContent.trim().startsWith('Walk Wolfie •'));if(label)label.textContent='Walk Wolfie • '+n+'/2';const old=[...card.children].find(x=>x.tagName==='BUTTON');if(old)old.remove();let box=card.querySelector('.wolfie-two');if(!box){box=d.createElement('div');box.className='wolfie-two';card.appendChild(box)}box.innerHTML='<button class="btn '+(n>=1?'good':'secondary')+'" data-w="1">'+(n>=1?'✓ Walk 1':'Walk 1')+'</button><button class="btn '+(n>=2?'good':'secondary')+'" data-w="2">'+(n>=2?'✓ Walk 2':'Walk 2')+'</button>';box.querySelectorAll('button').forEach(b=>b.onclick=e=>{e.stopPropagation();const t=Number(b.dataset.w),cur=getWalks();setWalks(cur===t?t-1:t);wolfie()})})}
 function ensureFuel(){let host=d.getElementById('fuelTodayV212');if(host)return host;const home=d.getElementById('homeView');if(!home)return null;const anchors=d.getElementById('anchorGrid')?.closest('.card');const card=d.createElement('div');card.className='card';card.id='fuelCardV212';card.innerHTML='<div class="label">🥗 Fuel Today</div><div class="small" style="margin-top:4px">Breakfast • snacks • lunch • dinner. Honest feedback, no all-or-nothing days.</div><div class="fuel-grid" id="fuelTodayV212"></div>';if(anchors)anchors.insertAdjacentElement('afterend',card);else home.appendChild(card);return card.querySelector('#fuelTodayV212')}
 function fuel(){const host=ensureFuel();if(!host)return;const x=read();x.fuelByDate=x.fuelByDate||{};const f=x.fuelByDate[date]||{};host.innerHTML=meals.map(m=>'<div class="fuel-row"><div class="fuel-name">'+m+'</div><div class="fuel-options">'+states.map(s=>'<button class="btn ghost fuel-btn '+(f[m]===s[0]?'active-'+s[0]:'')+'" data-m="'+m+'" data-s="'+s[0]+'">'+s[1]+' '+s[2]+'</button>').join('')+'</div></div>').join('')+'<div class="fuel-summary" id="fuelSummaryV212"></div>';host.querySelectorAll('button').forEach(b=>b.onclick=()=>{const y=read();y.fuelByDate=y.fuelByDate||{};const z=y.fuelByDate[date]||(y.fuelByDate[date]={});z[b.dataset.m]=z[b.dataset.m]===b.dataset.s?null:b.dataset.s;write(y);fuel()});const vals=meals.map(m=>f[m]).filter(Boolean),rough=vals.includes('rough'),clean=vals.filter(v=>v==='clean').length;d.getElementById('fuelSummaryV212').innerHTML='<div class="small">'+(!vals.length?'Nothing logged yet. No judgment — just information.':rough?'One rough meal doesn’t own the day. Next decision resets the trajectory.':clean>=3?'Strong fuel day. Keep stacking the boring wins.':'Keep logging. The goal is awareness, not perfection.')+'</div>'}
 function run(){wolfie();fuel()}
 run();setInterval(run,800);
}
const f=document.getElementById('app');if(f){f.addEventListener('load',()=>setTimeout(install,150));setTimeout(install,300)}
})();