/* Project 0→100 V2.5 — focused Fuel page + hydration + Wolfie 2x */
(function(){
const KEY='project0100_v4';
function install(){
 const frame=document.getElementById('app'),d=frame&&frame.contentDocument,w=frame&&frame.contentWindow;if(!d||!w)return;
 const date=new Date().toISOString().slice(0,10), meals=['Breakfast','Snack 1','Lunch','Snack 2','Dinner'];
 const states=[['clean','🟢','Ate clean'],['okay','🟡',"Could've been better"],['rough','🔴','I fucked up 😂'],['fasting','⚪','Fasted / skipped']];
 const read=()=>{try{return JSON.parse(w.localStorage.getItem(KEY)||'{}')}catch(e){return {}}};
 const write=x=>w.localStorage.setItem(KEY,JSON.stringify(x));
 const day=()=>{const x=read();x.fuelByDate=x.fuelByDate||{};x.fuelByDate[date]=x.fuelByDate[date]||{};return [x,x.fuelByDate[date]]};
 const walks=()=>Number((read().wolfieWalksByDate||{})[date]||0);
 if(!d.getElementById('v22style')){const s=d.createElement('style');s.id='v22style';s.textContent=`
 .wolfie-two{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:8px}.wolfie-two .btn{margin-top:0!important;padding:8px 3px!important;font-size:10px}
 .fuelHero{background:linear-gradient(135deg,rgba(53,215,239,.12),rgba(101,230,167,.08));border-color:#31505a}.fuelScore{font-size:38px;font-weight:950;margin-top:4px}.waterDots{display:grid;grid-template-columns:repeat(8,1fr);gap:6px;margin:12px 0}.waterDot{height:38px;border-radius:12px;border:1px solid #29313d;background:#0d1219;color:#94a0ae;font-weight:900}.waterDot.on{background:#123644;border-color:#35d7ef;color:#bff7ff}.mealStack{display:grid;gap:8px;margin-top:11px}.mealRow{background:#0d1219;border:1px solid #29313d;border-radius:15px;padding:12px;cursor:pointer}.mealRow .mealTop{display:flex;justify-content:space-between;align-items:center;gap:8px}.mealName{font-weight:900}.mealState{font-size:11px;color:#94a0ae}.mealChoices{display:none;grid-template-columns:1fr 1fr;gap:6px;margin-top:10px}.mealRow.open .mealChoices{display:grid}.mealChoices .btn{font-size:11px;padding:10px 6px}.fuelBack{margin-bottom:12px}.fuelAnchorProgress{font-size:10px;color:#94a0ae;margin-top:5px}
 `;d.head.appendChild(s)}
 function setWalk(n){const x=read();x.wolfieWalksByDate=x.wolfieWalksByDate||{};x.wolfieWalksByDate[date]=n;write(x)}
 function wolfie(){d.querySelectorAll('#anchorGrid .anchor,#anchorGridDay .anchor').forEach(card=>{if(!card.textContent.includes('Walk Wolfie'))return;const n=walks();card.classList.toggle('done',n>=2);const label=[...card.querySelectorAll('div')].find(x=>x.textContent.trim()==='Walk Wolfie'||x.textContent.trim().startsWith('Walk Wolfie •'));if(label)label.textContent='Walk Wolfie • '+n+'/2';const old=[...card.children].find(x=>x.tagName==='BUTTON');if(old)old.remove();let box=card.querySelector('.wolfie-two');if(!box){box=d.createElement('div');box.className='wolfie-two';card.appendChild(box)}box.innerHTML='<button class="btn '+(n>=1?'good':'secondary')+'" data-w="1">'+(n>=1?'✓ Walk 1':'Walk 1')+'</button><button class="btn '+(n>=2?'good':'secondary')+'" data-w="2">'+(n>=2?'✓ Walk 2':'Walk 2')+'</button>';box.querySelectorAll('button').forEach(b=>b.onclick=e=>{e.stopPropagation();const t=+b.dataset.w,cur=walks();setWalk(cur===t?t-1:t);wolfie()})})}
 function ensurePage(){if(d.getElementById('fuelView'))return;const app=d.querySelector('.app');if(!app)return;const sec=d.createElement('section');sec.id='fuelView';sec.className='view';sec.innerHTML=`<button class="btn ghost sm fuelBack" id="fuelBack">← Today</button><div class="kicker">FUEL + HYDRATION</div><div class="hero" style="font-size:34px">Fuel Today.</div><div class="sub">Notice it. Log it. Make the next choice.</div><div class="card fuelHero"><div class="label">Today's check-in</div><div class="fuelScore" id="fuelProgress">0/5</div><div class="small" id="fuelMessage">Awareness beats perfection.</div></div><div class="card"><div class="row"><div><div class="label">💧 Water</div><div class="med"><span id="waterCount">0</span>/8</div></div><button class="btn ghost sm" id="waterReset">Reset</button></div><div class="waterDots" id="waterDots"></div><div class="small">One tap = one glass/bottle. Keep it effortless.</div></div><div class="card"><div class="label">🥗 Meals</div><div class="small" style="margin-top:4px">Tap a meal. Make one honest choice. Move on.</div><div class="mealStack" id="mealStack"></div></div>`;app.appendChild(sec);d.getElementById('fuelBack').onclick=()=>show('homeView');d.getElementById('waterReset').onclick=()=>{const [x,f]=day();f.water=0;write(x);renderFuel()}}
 function show(id){d.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));d.getElementById(id)?.classList.add('active');w.scrollTo(0,0);if(id==='fuelView')renderFuel()}
 function wireAnchor(){d.querySelectorAll('#anchorGrid .anchor,#anchorGridDay .anchor').forEach(card=>{if(!card.textContent.includes('Fuel Check'))return;const [x,f]=day(),logged=meals.filter(m=>f[m]).length;card.classList.toggle('done',logged===5);let p=card.querySelector('.fuelAnchorProgress');if(!p){p=d.createElement('div');p.className='fuelAnchorProgress';const btn=[...card.children].find(x=>x.tagName==='BUTTON');if(btn)card.insertBefore(p,btn);else card.appendChild(p)}p.textContent=logged+'/5 meals logged';const btn=[...card.children].find(x=>x.tagName==='BUTTON');if(btn){btn.textContent=logged===5?'✓ Review':'Open';btn.onclick=e=>{e.stopPropagation();show('fuelView')}};card.onclick=()=>show('fuelView')})}
 function renderFuel(){ensurePage();const [x,f]=day(),logged=meals.filter(m=>f[m]).length,rough=meals.some(m=>f[m]==='rough'),clean=meals.filter(m=>f[m]==='clean').length;d.getElementById('fuelProgress').textContent=logged+'/5';d.getElementById('fuelMessage').textContent=rough?'One rough choice does not own the day. The next decision is fresh.':clean>=3?'You are stacking solid choices. Keep it simple.':logged?'Good. You are paying attention — keep going.':'Awareness beats perfection. Start with the next thing you eat.';const water=Math.max(0,Math.min(8,+f.water||0));d.getElementById('waterCount').textContent=water;d.getElementById('waterDots').innerHTML=Array.from({length:8},(_,i)=>'<button class="waterDot '+(i<water?'on':'')+'" data-water="'+(i+1)+'">'+(i<water?'💧':'＋')+'</button>').join('');d.querySelectorAll('#waterDots button').forEach(b=>b.onclick=()=>{const [a,z]=day();const n=+b.dataset.water;z.water=(+z.water||0)===n?n-1:n;write(a);renderFuel();wireAnchor()});d.getElementById('mealStack').innerHTML=meals.map(m=>{const cur=f[m],st=states.find(s=>s[0]===cur);return '<div class="mealRow" data-meal="'+m+'"><div class="mealTop"><div class="mealName">'+m+'</div><div class="mealState">'+(st?st[1]+' '+st[2]:'Not logged')+' ›</div></div><div class="mealChoices">'+states.map(s=>'<button class="btn '+(cur===s[0]?'good':'ghost')+'" data-state="'+s[0]+'">'+s[1]+' '+s[2]+'</button>').join('')+'</div></div>'}).join('');d.querySelectorAll('.mealRow').forEach(r=>{r.querySelector('.mealTop').onclick=()=>r.classList.toggle('open');r.querySelectorAll('button').forEach(b=>b.onclick=e=>{e.stopPropagation();const [a,z]=day();z[r.dataset.meal]=z[r.dataset.meal]===b.dataset.state?null:b.dataset.state;write(a);renderFuel();wireAnchor()})});wireAnchor()}
 function run(){ensurePage();wolfie();wireAnchor()}
 run();setInterval(run,900);
}
const f=document.getElementById('app');if(f){f.addEventListener('load',()=>setTimeout(install,180));setTimeout(install,350)}
})();