/* Project 0→100 V2.5 — timed missions + completion rewards */
(function(){
const KEY='project0100_v4';
function boot(){
 const f=document.getElementById('app'),d=f&&f.contentDocument,w=f&&f.contentWindow;if(!d||!w)return;
 const today=new Date().toISOString().slice(0,10);
 const read=()=>{try{return JSON.parse(w.localStorage.getItem(KEY)||'{}')}catch(e){return {}}};
 const write=x=>w.localStorage.setItem(KEY,JSON.stringify(x));
 if(!d.getElementById('v25style')){let s=d.createElement('style');s.id='v25style';s.textContent='.mission-time-row{display:grid;grid-template-columns:1fr 115px;gap:7px}.timed-mission{display:flex;gap:10px;align-items:center;padding:10px 0;border-bottom:1px solid #29313d}.mission-clock{min-width:72px;color:#35d7ef;font-weight:900;font-size:12px}.fortune{margin-top:12px;padding:16px;border:1px solid #5d4c2d;border-radius:18px;background:linear-gradient(135deg,rgba(255,200,107,.12),rgba(167,139,250,.07));text-align:center}.cookie{font-size:42px}.fortuneText{font-size:17px;font-weight:850;line-height:1.35;margin-top:8px}.completeMove{width:100%;margin-top:12px}.timed-title{font-size:11px;color:#94a0ae;margin-top:12px}';d.head.appendChild(s)}
 function timed(){let x=read();x.timedMissionsByDate=x.timedMissionsByDate||{};return x.timedMissionsByDate[today]||(x.timedMissionsByDate[today]=[])}
 function saveTimed(a){let x=read();x.timedMissionsByDate=x.timedMissionsByDate||{};x.timedMissionsByDate[today]=a;write(x)}
 function format(t){if(!t)return 'Anytime';let [h,m]=t.split(':').map(Number),ap=h>=12?'PM':'AM';h=h%12||12;return h+':'+String(m).padStart(2,'0')+' '+ap}
 function ensureMissionUI(){const input=d.getElementById('missionInput');if(!input||d.getElementById('missionTime'))return;const stack=input.parentElement;if(!stack)return;const wrap=d.createElement('div');wrap.className='mission-time-row';stack.insertBefore(wrap,input);wrap.appendChild(input);const time=d.createElement('input');time.type='time';time.id='missionTime';time.setAttribute('aria-label','Optional mission time');wrap.appendChild(time);const add=[...stack.querySelectorAll('button')].find(b=>b.textContent.includes('Add Mission'));if(add){const old=add.onclick;add.onclick=e=>{const txt=input.value.trim(),tm=time.value;if(tm&&txt){e.preventDefault();let a=timed();a.push({id:Date.now(),text:txt,time:tm,done:false});saveTimed(a);input.value='';time.value='';renderTimed();return false}if(old)return old.call(add,e)}}}
 function renderTimed(){const base=d.getElementById('missionList');if(!base)return;let host=d.getElementById('timedMissionList');if(!host){host=d.createElement('div');host.id='timedMissionList';base.parentElement.insertBefore(host,base)}const a=timed().slice().sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'));host.innerHTML=a.length?'<div class="timed-title">SCHEDULED</div>'+a.map(m=>'<div class="timed-mission"><input class="check" type="checkbox" data-id="'+m.id+'" '+(m.done?'checked':'')+'><div class="mission-clock">'+format(m.time)+'</div><div class="'+(m.done?'doneText':'')+'" style="flex:1">'+m.text+'</div><button class="btn ghost sm" data-del="'+m.id+'">×</button></div>').join(''):'';host.querySelectorAll('[data-id]').forEach(c=>c.onchange=()=>{let z=timed(),m=z.find(q=>q.id==c.dataset.id);if(m)m.done=c.checked;saveTimed(z);renderTimed();updateNext()});host.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{saveTimed(timed().filter(q=>q.id!=b.dataset.del));renderTimed();updateNext()});const dayHost=d.getElementById('missionListDay');if(dayHost){let h=d.getElementById('timedMissionListDay');if(!h){h=d.createElement('div');h.id='timedMissionListDay';dayHost.parentElement.insertBefore(h,dayHost)}h.innerHTML=host.innerHTML}}
 function updateNext(){const now=new Date(),mins=now.getHours()*60+now.getMinutes(),a=timed().filter(m=>!m.done&&m.time).map(m=>({...m,n:+m.time.slice(0,2)*60 + +m.time.slice(3)})).filter(m=>m.n>=mins).sort((a,b)=>a.n-b.n);if(!a.length)return;const m=a[0],el=d.getElementById('nextMove');if(el&&m.n-mins<=180)el.textContent='⏰ '+format(m.time)+' — '+m.text}
 const fortunes=['You didn’t need motivation. You needed a start.','The obstacle became the workout.','Five minutes counts. You kept the promise.','Momentum is built in embarrassingly small pieces.','Do the next right thing. Then do it again.','You are becoming someone who follows through.','Small wins are how the comeback gets teeth.','Discipline is remembering what you wanted.','Today does not need to be perfect to matter.','Plot twist: you actually did the thing. 😂','The boring win still counts as a win.','You moved. The day moved with you.'];
 function cookie(panel){panel.innerHTML='<div class="fortune"><div class="cookie">🥠</div><div class="label">FORTUNE UNLOCKED</div><div class="fortuneText">'+fortunes[Math.floor(Math.random()*fortunes.length)]+'</div><button class="btn primary" style="margin-top:12px" id="cookieDone">Back to Today</button></div>';d.getElementById('cookieDone').onclick=()=>{panel.classList.remove('show');panel.innerHTML=''}}
 function rewardMove(){const p=d.getElementById('actionPanel');if(!p||!p.classList.contains('show')||p.querySelector('.completeMove')||p.querySelector('.fortune'))return;if(!p.textContent.trim())return;const b=d.createElement('button');b.className='btn good completeMove';b.textContent='✓ COMPLETED';b.onclick=()=>cookie(p);p.appendChild(b)}
 function run(){ensureMissionUI();renderTimed();updateNext();rewardMove()}
 run();setInterval(run,900)
}
const f=document.getElementById('app');if(f){f.addEventListener('load',()=>setTimeout(boot,220));setTimeout(boot,500)}
})();