/* Project 0→100 V2.6 — score truth + gambling confirmation + Brain Dump */
(function(){
const PATCH='project0100_v26';
const APPKEY='project0100_v4';
const day=()=>new Date().toISOString().slice(0,10);
function boot(){
 const f=document.getElementById('app'),d=f&&f.contentDocument,w=f&&f.contentWindow;if(!d||!w)return;
 const readPatch=()=>{try{return JSON.parse(w.localStorage.getItem(PATCH)||'{}')}catch(e){return {}}};
 const writePatch=x=>w.localStorage.setItem(PATCH,JSON.stringify(x));
 const readApp=()=>{try{return JSON.parse(w.localStorage.getItem(APPKEY)||'{}')}catch(e){return {}}};
 const writeApp=x=>w.localStorage.setItem(APPKEY,JSON.stringify(x));
 function css(){if(d.getElementById('v26style'))return;let s=d.createElement('style');s.id='v26style';s.textContent=`
 .v26-action{margin-top:10px;width:100%}.v26-mini{font-size:11px;color:#94a0ae;margin-top:7px;line-height:1.4}
 .brain-card{border-color:#31505a}.brain-input{min-height:105px}.brain-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:9px}
 .heard{margin-top:10px;display:grid;gap:7px}.heard-item{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;background:#0d1219;border:1px solid #29313d;border-radius:13px;padding:10px}
 .heard-cat{font-size:9px;letter-spacing:.12em;color:#35d7ef;text-transform:uppercase;font-weight:900}.score-note{font-size:10px;color:#65e6a7;margin-top:6px}
 `;d.head.appendChild(s)}
 function gambling(){let x=readPatch();x.gambling=x.gambling||{confirmed:{},streak:0,last:null};return x.gambling}
 function saveGambling(g){let x=readPatch();x.gambling=g;writePatch(x)}
 function dateDiff(a,b){return Math.round((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/86400000)}
 function confirmGambling(){let g=gambling(),t=day();if(g.confirmed[t])return;if(g.last&&dateDiff(g.last,t)===1)g.streak=(g.streak||0)+1;else if(g.last!==t)g.streak=1;g.last=t;g.confirmed[t]=true;saveGambling(g);renderGambling();recalcScore();if(g.streak===7||[14,30,60,90,100,365].includes(g.streak))fortune(g.streak)}
 function resetGambling(){let g=gambling(),t=day();g.confirmed[t]=false;g.streak=0;g.last=null;saveGambling(g);renderGambling();recalcScore()}
 function fortune(n){const p=d.getElementById('actionPanel');if(!p)return;const lines=['You kept the promise when nobody was watching.','Momentum is built one clean decision at a time.','The streak is evidence. Keep becoming the person who follows through.','You chose the life you want over the impulse you do not.'];p.classList.add('show');p.innerHTML='<div class="fortune"><div class="cookie">🥠</div><div class="label">'+n+' DAY STREAK</div><div class="fortuneText">'+lines[Math.floor(Math.random()*lines.length)]+'</div><button class="btn primary" style="margin-top:12px" id="v26FortuneDone">Keep Moving</button></div>';d.getElementById('v26FortuneDone').onclick=()=>{p.classList.remove('show');p.innerHTML=''}}
 function renderGambling(){const el=d.getElementById('gambleDays');if(!el)return;const card=el.closest('.card'),g=gambling(),t=day();el.textContent=g.streak||0;const bar=d.getElementById('gambleBar');if(bar)bar.style.width=Math.min(100,(g.streak||0)/90*100)+'%';let host=d.getElementById('v26GambleAction');if(!host){host=d.createElement('div');host.id='v26GambleAction';card.appendChild(host)}host.innerHTML=g.confirmed[t]?'<button class="btn good v26-action" id="v26GambleDone">✓ No Gambling Today</button><div class="v26-mini">Confirmed for today. Tap below only if you need to correct it.</div><button class="btn ghost sm v26-action" id="v26GambleReset">Reset / I gambled today</button>':'<button class="btn primary v26-action" id="v26GambleConfirm">✓ NO GAMBLING TODAY</button><div class="v26-mini">Confirm it intentionally. A day never counts just because the clock passed midnight.</div>';const c=d.getElementById('v26GambleConfirm');if(c)c.onclick=confirmGambling;const r=d.getElementById('v26GambleReset');if(r)r.onclick=resetGambling}
 function completedAnchors(){const grid=d.getElementById('anchorGrid');if(!grid)return {done:0,total:3};const cards=[...grid.querySelectorAll('.anchor')];let done=cards.filter(a=>a.classList.contains('done')||/✓|done|2\/2|5\/5/i.test(a.textContent)).length;return {done,total:cards.length||3}}
 function hydrationDone(){const app=readApp(),t=day();const possible=[app.nutritionByDate&&app.nutritionByDate[t],app.nutrition&&app.nutrition[t],app.todayNutrition];for(const n of possible){if(n&&(Number(n.water)>0||Number(n.waterL)>0||Number(n.hydration)>0))return true}const txt=d.body.innerText;return /water[^\n]{0,30}(done|✓|goal|complete)/i.test(txt)||/hydration[^\n]{0,30}(done|✓|goal|complete)/i.test(txt)}
 function recalcScore(){const a=completedAnchors(),g=gambling(),t=day();let score=0;
 // Core 100: Wolfie 20 + Train 25 + Fuel 20 + Hydration 15 + Gambling-free 20.
 const grid=d.getElementById('anchorGrid');if(grid){const cards=[...grid.querySelectorAll('.anchor')];cards.forEach(c=>{const txt=c.textContent.toLowerCase(),done=c.classList.contains('done')||/✓|done|2\/2|5\/5/i.test(c.textContent);if(!done)return;if(txt.includes('wolf'))score+=20;else if(txt.includes('train')||txt.includes('workout'))score+=25;else if(txt.includes('fuel')||txt.includes('meal')||txt.includes('food'))score+=20})}
 if(hydrationDone())score+=15;if(g.confirmed[t])score+=20;score=Math.min(100,score);const el=d.getElementById('score'),bar=d.getElementById('scoreBar');if(el)el.textContent=score;if(bar)bar.style.width=score+'%';const count=d.getElementById('anchorCount');if(count)count.textContent=a.done+'/'+a.total;let note=d.getElementById('v26ScoreNote');if(el&&!note){note=d.createElement('div');note.id='v26ScoreNote';note.className='score-note';el.closest('.card').appendChild(note)}if(note)note.textContent='Live from completed actions';return score}
 function brainUI(){if(d.getElementById('v26Brain'))return;const tasks=d.getElementById('tasksView');if(!tasks)return;const first=tasks.querySelector('.card');const card=d.createElement('div');card.className='card brain-card';card.id='v26Brain';card.innerHTML='<div class="row"><div><div class="label">🧠 Brain Dump</div><div class="small">Talk or type. Get it out of your head.</div></div><span class="pill">ASTARI STYLE</span></div><textarea class="brain-input" id="brainText" placeholder="Example: Walk Wolfie, call Phil, drink water, send the Dam roster, work out, pay Chase…"></textarea><div class="brain-actions"><button class="btn secondary" id="brainMic">🎙️ Talk</button><button class="btn primary" id="brainSort">✨ Sort It</button></div><div id="brainHeard"></div>';tasks.insertBefore(card,first);d.getElementById('brainSort').onclick=sortBrain;d.getElementById('brainMic').onclick=startVoice}
 function splitThoughts(t){return t.split(/\n|,|;|\band then\b|\bthen\b/gi).map(x=>x.trim()).filter(x=>x.length>2)}
 function category(x){const s=x.toLowerCase();if(/wolf|walk/.test(s))return 'Today';if(/workout|gym|swim|kayak|handstand|train/.test(s))return 'Workout';if(/water|meal|food|protein|eat/.test(s))return 'Fuel';if(/dam|roster|guest|tour|venture|client|call|email|send/.test(s))return 'Important';if(/pay|card|chase|discover|rei|debt|bill/.test(s))return 'War Room';return 'Pile'}
 function sortBrain(){const input=d.getElementById('brainText'),host=d.getElementById('brainHeard');const items=splitThoughts(input.value).map((text,i)=>({id:Date.now()+i,text,cat:category(text)}));let x=readPatch();x.brainDraft=items;writePatch(x);host.className='heard';host.innerHTML=items.length?'<div class="label">HERE’S WHAT I HEARD</div>'+items.map(i=>'<div class="heard-item"><div><div class="heard-cat">'+i.cat+'</div><div>'+i.text+'</div></div><button class="btn ghost sm" data-brain="'+i.id+'">×</button></div>').join('')+'<button class="btn good" id="brainAddAll">✓ Add to My Day / Pile</button>':'<div class="v26-mini">Give me a few thoughts first.</div>';host.querySelectorAll('[data-brain]').forEach(b=>b.onclick=()=>{let z=readPatch();z.brainDraft=(z.brainDraft||[]).filter(i=>i.id!=b.dataset.brain);writePatch(z);renderDraft()});const add=d.getElementById('brainAddAll');if(add)add.onclick=addBrain}
 function renderDraft(){const host=d.getElementById('brainHeard'),x=readPatch(),items=x.brainDraft||[];if(!host)return;host.className='heard';host.innerHTML=items.length?'<div class="label">HERE’S WHAT I HEARD</div>'+items.map(i=>'<div class="heard-item"><div><div class="heard-cat">'+i.cat+'</div><div>'+i.text+'</div></div><button class="btn ghost sm" data-brain="'+i.id+'">×</button></div>').join('')+'<button class="btn good" id="brainAddAll">✓ Add to My Day / Pile</button>':'';host.querySelectorAll('[data-brain]').forEach(b=>b.onclick=()=>{let z=readPatch();z.brainDraft=(z.brainDraft||[]).filter(i=>i.id!=b.dataset.brain);writePatch(z);renderDraft()});const add=d.getElementById('brainAddAll');if(add)add.onclick=addBrain}
 function addBrain(){let x=readPatch(),items=x.brainDraft||[],app=readApp();app.pile=app.pile||[];items.forEach(i=>app.pile.push({id:Date.now()+Math.random(),text:i.text,priority:i.cat==='Important'?'important':i.cat==='War Room'?'important':'should',done:false}));writeApp(app);x.brainDraft=[];writePatch(x);const input=d.getElementById('brainText');if(input)input.value='';renderDraft();try{if(typeof w.renderAll==='function')w.renderAll();else if(typeof w.renderPile==='function')w.renderPile()}catch(e){} }
 function startVoice(){const SR=w.SpeechRecognition||w.webkitSpeechRecognition,btn=d.getElementById('brainMic');if(!SR){btn.textContent='Voice not available';return}const r=new SR();r.continuous=false;r.interimResults=false;r.lang='en-US';btn.textContent='Listening…';r.onresult=e=>{const t=e.results[0][0].transcript,inp=d.getElementById('brainText');inp.value+=(inp.value?'\n':'')+t;btn.textContent='🎙️ Talk'};r.onerror=r.onend=()=>btn.textContent='🎙️ Talk';r.start()}
 function run(){css();renderGambling();brainUI();recalcScore()}
 run();setInterval(run,700);
 }
 const f=document.getElementById('app');if(f){f.addEventListener('load',()=>setTimeout(boot,250));setTimeout(boot,650)}
})();