/* Project 0→100 V2.9.1 — coach interaction fix */
(function(){
 function boot(){
  const f=document.getElementById('app'),d=f&&f.contentDocument,w=f&&f.contentWindow;if(!d||!w)return;
  const card=d.getElementById('v29Coach');if(!card)return;
  const KEY='project0100_v4',day=()=>new Date().toISOString().slice(0,10),read=()=>{try{return JSON.parse(w.localStorage.getItem(KEY)||'{}')}catch(e){return {}}};
  function snap(){const cards=[...(d.getElementById('anchorGrid')?.querySelectorAll('.anchor')||[])];let wolf=false,train=false,fuel=false;cards.forEach(c=>{const t=c.textContent.toLowerCase(),done=c.classList.contains('done')||/✓|done|2\/2|5\/5/i.test(c.textContent);if(t.includes('wolf'))wolf=done;else if(t.includes('train')||t.includes('workout'))train=done;else if(t.includes('fuel')||t.includes('meal')||t.includes('food'))fuel=done});const s=read(),fd=(s.fuelByDate||{})[day()]||{},water=Math.max(0,Math.min(8,Number(fd.water)||0)),clean=!!d.getElementById('v26GambleDone');return{wolf,train,fuel,water,clean,score:(wolf?20:0)+(train?25:0)+(fuel?20:0)+(water>=8?15:0)+(clean?20:0)}}
  function advice(mode){const x=snap();if(mode==='push'&&!x.train)return['Go train now.','Training is the biggest unfinished physical lever today.','Open Body and start the first exercise.'];if(mode==='simplify'){if(!x.wolf)return['Make today smaller.','One useful move is enough to restart momentum.','Walk Wolfie.'];if(!x.water||x.water<8)return['Close the easy loop.','You do not need another project right now.','Finish today’s water.']}if(mode==='surprise')return[['Change the scenery.','Break autopilot for ten minutes.','Go outside with no scrolling.'],['Add some joy.','Your 100 is a life, not only productivity.','Do one thing purely because it sounds fun.'],['Create evidence.','A finished tiny action beats another plan.','Finish the smallest unfinished thing.']][Math.floor(Math.random()*3)];if(!x.wolf)return['Take Wolfie out.','It moves an anchor and changes your environment at the same time.','Walk Wolfie — phone in pocket.'];if(!x.train)return['Move your body next.','Your score is '+x.score+'/100 and training is still open.','Open Body and start.'];if(x.water<8)return['Finish the easy points.','Close the water loop before adding another task.','Finish today’s water.'];if(!x.clean)return['Protect the streak.','The clean choice reinforces the person you are becoming.','Lock in today’s clean choice.'];return['You earned some life.','More productivity is not automatically better.','Choose something fun, social, adventurous, or restful.']}
  function show(mode){const a=advice(mode||'coach'),box=d.getElementById('v291Result')||(()=>{const z=d.createElement('div');z.id='v291Result';z.className='panel show';card.appendChild(z);return z})();box.classList.add('show');box.innerHTML='<div class="label">✨ YOUR COACH</div><div class="missionText">'+a[0]+'</div><div class="small" style="margin-top:8px">'+a[1]+'</div><div style="margin-top:11px;padding:12px;border:1px solid #31505a;border-radius:14px"><div class="label">DO THIS NEXT</div><strong>'+a[2]+'</strong></div><button class="btn secondary sm" style="width:100%;margin-top:10px" id="v291Again">Give me another</button>';d.getElementById('v291Again').onclick=()=>show('surprise');box.scrollIntoView({behavior:'smooth',block:'nearest'})}
  const ask=d.getElementById('v29Ask');if(ask)ask.onclick=function(e){e.preventDefault();e.stopPropagation();show('coach')};
  card.querySelectorAll('[data-m]').forEach(b=>b.onclick=function(e){e.preventDefault();e.stopPropagation();show(b.dataset.m)});
 }
 const f=document.getElementById('app');if(f){f.addEventListener('load',()=>setTimeout(boot,900));setTimeout(boot,1600)}
})();